In [1]:
import os
import csv

In [2]:
for j, station_path in enumerate([os.path.join('meteostations', 'station1'), os.path.join('meteostations', 'station2')]):
    rows = []
    for i, csvpath in enumerate(os.listdir(station_path)):
        print('Processing.. {}'.format(csvpath))
        with open(os.path.join(station_path, csvpath), 'r') as csvfile:
            for k, row in enumerate(csvfile):
                if i != 0 and k == 0:
                    continue
                rows.append(row)
    with open('meteo_{}.csv'.format(j+1), 'w') as csvfile:
        for row in rows:
            csvfile.write(row)

Processing.. meteo_1_2018-01-01_2018-12-31.csv
Processing.. meteo_1_2021-01-01_2021-12-31.csv
Processing.. meteo_1_2022-01-01_2022-12-31.csv
Processing.. meteo_1_2019-01-01_2019-12-31.csv
Processing.. meteo_1_2020-01-01_2020-12-31.csv
Processing.. meteo_1_2017-01-01_2017-12-31.csv
Processing.. meteo_2_2020-01-01_2020-12-31.csv
Processing.. meteo_2_2022-01-01_2022-12-31.csv
Processing.. meteo_2_2019-01-01_2019-12-31.csv
Processing.. meteo_2_2018-01-01_2018-12-31.csv
Processing.. meteo_2_2017-01-01_2017-12-31.csv
Processing.. meteo_2_2021-01-01_2021-12-31.csv


In [1]:
import dill
import numpy as np

In [3]:
with open('Dolgoprudnyj.dump', 'rb') as dump:
    data = dill.load(dump)
list(data.keys())

[(2022, 10, 1, 0),
 (2022, 10, 1, 12),
 (2022, 10, 2, 0),
 (2022, 10, 2, 12),
 (2022, 10, 3, 0),
 (2022, 10, 13, 12),
 (2022, 10, 14, 0),
 (2022, 10, 14, 12),
 (2022, 10, 15, 0),
 (2022, 10, 15, 12),
 (2022, 10, 16, 0),
 (2022, 10, 16, 12),
 (2022, 10, 17, 12),
 (2022, 10, 18, 0),
 (2022, 10, 18, 12),
 (2022, 10, 19, 0),
 (2022, 10, 19, 12),
 (2022, 10, 20, 0),
 (2022, 10, 20, 12),
 (2022, 10, 21, 0),
 (2022, 10, 21, 12),
 (2022, 10, 22, 0),
 (2022, 10, 22, 12),
 (2022, 10, 23, 0),
 (2022, 10, 23, 12),
 (2022, 10, 24, 0),
 (2022, 10, 24, 12),
 (2022, 10, 25, 0),
 (2022, 10, 25, 12),
 (2022, 10, 26, 0),
 (2022, 10, 26, 12),
 (2022, 10, 27, 0),
 (2022, 10, 27, 12),
 (2022, 10, 28, 0),
 (2022, 10, 29, 0),
 (2022, 10, 29, 12),
 (2022, 10, 30, 0),
 (2022, 10, 30, 12),
 (2022, 8, 1, 0),
 (2022, 8, 1, 12),
 (2022, 8, 2, 0),
 (2022, 8, 2, 12),
 (2022, 8, 3, 0),
 (2022, 8, 3, 12),
 (2022, 8, 4, 0),
 (2022, 8, 4, 12),
 (2022, 8, 5, 0),
 (2022, 8, 5, 12),
 (2022, 8, 6, 0),
 (2022, 8, 6, 12),
 (20

In [14]:
data[tuple([2022, 10, 1, 0])]

(array([12.4, 11.5, 10.7,  9.8,  8.7,  7. ]),
 array([994., 970., 947., 925., 895., 850.]),
 array([91., 93., 95., 97., 97., 97.]),
 array([0.187, 0.393, 0.594, 0.792, 1.068, 1.5  ]))